#!/usr/bin/python


import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

import roman

class RomanWindow(Gtk.Window):

    def __init__(self):
        # Main Gtk.Window() setup
        Gtk.Window.__init__(self, title="PyRoman")
        
        # Create a new Grid() for layout
        grid = Gtk.Grid()
        self.add(grid)

        # Text labels
        self.label_pyroman = Gtk.Label()
        self.label_input = Gtk.Label()
        self.label_output = Gtk.Label()

        self.label_pyroman.set_markup("<big>PyRoman</big>\n© ncdulo 2019")
        self.label_input.set_text("Input:")
        self.label_output.set_text("Output:")

        # Text entry
        self.entry_input = Gtk.Entry()
        self.entry_output = Gtk.Entry()

        self.entry_output.set_editable(None)

        # Buttons
        self.button_convert = Gtk.Button(label="Convert")
        self.button_quit = Gtk.Button(label="Quit")

        # Callbacks
        self.button_convert.connect("clicked", self.on_convert_clicked)
        self.button_quit.connect("clicked", Gtk.main_quit)

        # Add it all to the Grid()

        # Grid.attach(child, left, top, width, height)
        # Grid.attach_next_to(child, sibling, side, width, height)

        # Original grid, reference material
        #grid.add(self.button_convert)
        #grid.attach_next_to(self.button_quit, self.button_convert, Gtk.PositionType.RIGHT, 2, 1)
        #grid.attach(self.label_pyroman, 0, 1, 2, 1)
        # The real grid
        # Top Row (title, description)
        grid.add(self.label_pyroman)

        # Input row
        grid.attach(self.label_input, 0, 1, 1, 1)
        grid.attach_next_to(self.entry_input, self.label_input, Gtk.PositionType.RIGHT, 1, 1)

        # Output row
        grid.attach(self.label_output, 0, 2, 1, 1)
        grid.attach_next_to(self.entry_output, self.label_output, Gtk.PositionType.RIGHT, 1, 1)

        # Mode row

        # Button/Command row
        grid.attach(self.button_convert, 0, 3, 1, 1)
        grid.attach_next_to(self.button_quit, self.button_convert, Gtk.PositionType.RIGHT, 2, 1)


    # Callback defs

    # Convert button has been pressed
    def on_convert_clicked(self, widget):
        input_text = self.entry_input.get_text()
        print(input_text)
        self.entry_output.set_text(roman.to_roman(input_text))

# Create an instance of our window class and display it
win = RomanWindow()
win.connect("destroy", Gtk.main_quit)
win.show_all()

# Enter main GTK event processing loop
Gtk.main()

